version: '3'

services:
  headline_collector:
    build: job_collector
    volumes:
      - ./job_collector/:/app
    depends_on:
      - headline_mongo
  
  headline_mongo:
    image: mongo
    ports:
      - 27017:27017

  headline_etl:
    build: job_etl
    volumes:
      - ./job_etl/:/app
    depends_on:
      - headline_mongo
      - headline_postgres

  headline_postgres:
    image: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=headline_pgdb




